services:
  mysql:
    image: mysql:8.4
    container_name: techkrush-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-techkrush}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u${DB_USERNAME:-root}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: techkrush-pma
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: "root"
      PMA_PASSWORD: ${DB_PASSWORD:-root}
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db_data:
    driver: local
